#' Calibrate Self-Reported MEPS Values into Continuous Age-Adjusted Copula Space
#' 
#' @param meps_data Cleaned target MEPS dataset containing self-reported values.
#' @param reported_var Character string of the column name containing self-reported values.
#' @param qr_grid A fitted quantile grid object generated by `fit_age_spline_quantiles`.
#' @param tau_seq Numeric vector of quantiles matching the grid setup.
#' @return A continuous numeric vector of length nrow(meps_data) containing de-heaped, age-conditional U(0,1) percentiles.
#' @export
meps_quantreg_calibrate = function(meps_data, reported_var, qr_grid, tau_seq = c(seq(0.01, 0.95, by = 0.01), seq(0.96, 0.999, by = 0.001))) {
  predicted_matrix = predict(qr_grid, newdata = meps_data)
  meps_calibrated_pit = numeric(nrow(meps_data))
  
  for (i in 1:nrow(meps_data)) {
    reported_val = meps_data[[reported_var]][i]
    age_conditional_line = predicted_matrix[i, ]
    age_conditional_line = sort(age_conditional_line) # Rearrangement to prevent crossing
    closest_tau_idx = which.min(abs(age_conditional_line - reported_val))
    meps_calibrated_pit[i] = tau_seq[closest_tau_idx]
  }
  return(meps_calibrated_pit)
}

#' Master Stratified Calibration Pipeline for MEPS Data
#' 
#' @param meps_data Cleaned target MEPS dataset containing self-reported values.
#' @param nhanes_data Cleaned reference dataset containing objectively measured metrics.
#' @param reported_var Character string of the column name containing self-reported values in MEPS.
#' @param measured_var Character string of the column name containing measured values in NHANES.
#' @param truncation_val The numeric threshold where the survey implements top-coding.
#' @param strata_vars Character vector of column names to stratify by (e.g., c("sex", "race")).
#' @param df Degrees of freedom for the continuous natural cubic age spline. Default is 3.
#' @return A numeric vector matching the row count of meps_data containing fully calibrated percentiles.
#' @export
meps_calibrate_pipeline = function(meps_data, nhanes_data, reported_var, measured_var, truncation_val, strata_vars, df = 3) {
  
  fine_tau = c(seq(0.01, 0.95, by = 0.01), seq(0.96, 0.999, by = 0.001))
  
  # Create a unique interaction key for stratification across both datasets
  meps_key = apply(meps_data[, strata_vars, drop = FALSE], 1, paste, collapse = "_")
  nhanes_key = apply(nhanes_data[, strata_vars, drop = FALSE], 1, paste, collapse = "_")
  unique_strata = unique(meps_key)
  
  # Pre-allocate final output vector
  final_calibrated_vector = numeric(nrow(meps_data))
  
  # Loop over each demographic stratum independently
  for (stratum in unique_strata) {
    meps_idx = which(meps_key == stratum)
    nhanes_idx = which(nhanes_key == stratum)
    
    # Safety check: skip if a demographic cell lacks reference data
    if (length(nhanes_idx) < 30) {
      warning(paste("Stratum", stratum, "has insufficient NHANES data. Skipping calibration for these rows."))
      final_calibrated_vector[meps_idx] = NA
      next
    }
    
    # Isolate subset data frames
    meps_sub = meps_data[meps_idx, , drop = FALSE]
    nhanes_sub = nhanes_data[nhanes_idx, , drop = FALSE]
    
    # Fit the continuous age-spline quantile grid for this specific demographic group
    qr_grid = fit_age_spline_quantiles(
      nhanes_data = nhanes_sub, 
      response_var = measured_var, 
      df = df, 
      tau_seq = fine_tau
    )
    
    # Run the inversion and tail extrapolation for this specific group
    calibrated_sub = meps_extrapolate_tail(
      meps_data = meps_sub, 
      reported_var = reported_var, 
      truncation_val = truncation_val, 
      qr_grid = qr_grid, 
      tau_seq = fine_tau
    )
    
    # Assign the results back to the correct original row indexes
    final_calibrated_vector[meps_idx] = calibrated_sub
  }
  
  return(final_calibrated_vector)
}
