#' Impute Ranks for Truncated Upper Tails Using an Age-Conditional Reference
#' 
#' @param meps_data Cleaned target MEPS dataset containing self-reported values.
#' @param reported_var Character string of the column name containing self-reported values.
#' @param truncation_val The numeric threshold where the survey implements top-coding.
#' @param qr_grid A fitted quantile grid object generated by `fit_age_spline_quantiles` on NHANES data.
#' @param tau_seq Numeric vector of quantiles matching the grid setup.
#' @return A numeric vector of length nrow(meps_data) containing continuous, de-truncated U(0,1) percentiles.
#' @export
meps_extrapolate_tail = function(meps_data, reported_var, truncation_val, qr_grid, tau_seq = c(seq(0.01, 0.95, by = 0.01), seq(0.96, 0.999, by = 0.001))) {
  
  # Run base calibration
  meps_pit = meps_quantreg_calibrate(meps_data, reported_var, qr_grid, tau_seq)
  
  # Identify who is sitting on the truncation wall with a small precision cushion
  is_truncated = (meps_data[[reported_var]] >= (truncation_val - 1e-5))
  n_truncated = sum(is_truncated)
  
  if (n_truncated > 0) {
    lower_bounds = meps_pit[is_truncated]
    
    # Force a lower ceiling for drawing the tail to prevent sampling errors
    lower_bounds = ifelse(lower_bounds >= 0.99, 0.95, lower_bounds)
    
    # Vectorized random uniform allocation past the boundary
    stochastic_tails = runif(n_truncated, min = lower_bounds, max = 0.999)
    meps_pit[is_truncated] = stochastic_tails
  }
  
  return(meps_pit)
}
